version: '3'

services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes: 
      - ../volumes/jenkins/_data:/var/jenkins_home/
    networks:
      - driver_network  
  ubuntu_slave:
    depends_on: 
      - jenkins
    container_name: ubuntucomposeslave
    volumes:
      - /var/run/docker.sock/:/var/run/docker.sock/
    build: 
      context: ../dockerfiles/slave/
    command: java -jar agent.jar -jnlpUrl http://jenkins:8080/computer/Slave/jenkins-agent.jnlp -secret 173dd35b41c234bd723e0793625842909bf5311aa468efb45c4164f6ab2d86a5 -workDir "/home/"
    networks:
      - driver_network
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    container_name: artifactory
    networks:
      - driver_network
    volumes: 
      - ../volumes/artifactory/_data:/var/opt/jfrog/artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
  selenium_hub:
    image: selenium/hub
    container_name: seleniumhubcompose
    ports: 
      - "4444:4444"
    networks: 
      - driver_network
  selenium_firefox:
    image: selenium/node-firefox
    container_name: firefoxcompose
    depends_on: 
      - selenium_hub
    environment: 
      - HUB_HOST=seleniumhubcompose
      - HUB_PORT=4444
    networks: 
      - driver_network
networks:
  driver_network:
    driver: bridge